### ISSUE TITLE
can't store manual payments settings

### ISSUE THREAD

**Issue by mgarub** [openstore-ecommerce/OpenStore#108]
Hi,

I have two problems with manual payment that might be connected.

Like in an earlier issue i am getting an error on manual payment:

![payment](https://user-images.githubusercontent.com/23345646/94296567-55875880-ff63-11ea-87bc-3f451cf69b5b.JPG)

Then i tried to save my manual payment  setting but i get an error ** No action **

![manualpayment](https://user-images.githubusercontent.com/23345646/94296774-adbe5a80-ff63-11ea-8045-e240c796cb2c.JPG)

as you maybe see i did some translation direct in the xml file. Because of the ** No action ** issue i guess my changes does not apply and produce the razor error.

i have OS 4.1.3 installed.

Is this a known issue ?

Kind regards
Martin Gartmann

**Comment by leedavi** [comment]
This is not a known issue.  The "No Action" message appears when the command sent to the server does not exist??

I'm at a lost to explain it, without more information.

Can you give me access?  If so, send me a private message on the forum.  And I'll login and have a quick look for you.

https://forum.openstore-ecommerce.com/

**Comment by mgarub** [comment]
What kind of access do you need. 
DNN admin or FTP to root of DNN installation.

**Comment by leedavi** [comment]
Admin or host. I'll just have a quick look for anything obvious.  And will not change anything.

**Comment by leedavi** [comment]
OK, I have had a quick look.  The only issue I can see is the error in the DNN error log.  It fails when reading the de-de resx file.  Maybe this has a knock on effect.  I would try fixing that... or try to delete the de-de resx and see if it works on the default resx file.

**Comment by mgarub** [comment]
Dear David,
i have fixed these errors. in some translation special geman characters seems to make problems, but not on all pages.
also i have deleted the de-de for manual payment with no success.
may i use debug mode to find the problem?
kind regards
Martin


----- Original-Nachricht -----
Von: David Lee (notifications@github.com)
Datum: 29-09-2020 05:38
An: openstore-ecommerce/OpenStore (OpenStore@noreply.github.com)
Cc: Martin Gartmann (info@ayl-webdesign.de), Author (author@noreply.github.com)
Betreff: [Spam] Re: [openstore-ecommerce/OpenStore] can't store manual payments settings (#108)

OK, I have had a quick look. The only issue I can see is the error in the DNN error log. It fails when reading the de-de resx file. Maybe this has a knock on effect. I would try fixing that... or try to delete the de-de resx and see if it works on the default resx file.

**Comment by mgarub** [comment]
Hi David,
the problem seems to be solved. i completly remove the manual payment provider and reinstalled it with the setting from a fresh OS 4.1.3 install with the standard setiings from another brandnew dnn install.
as far as i remember the ajax provider was not there in the failty installation. not it seems to work.
Anyway thanks for your uick reply in the case.

Kind regards
Martin


----- Original-Nachricht -----
Von: David Lee (notifications@github.com)
Datum: 29-09-2020 05:38
An: openstore-ecommerce/OpenStore (OpenStore@noreply.github.com)
Cc: Martin Gartmann (info@ayl-webdesign.de), Author (author@noreply.github.com)
Betreff: [Spam] Re: [openstore-ecommerce/OpenStore] can't store manual payments settings (#108)

OK, I have had a quick look. The only issue I can see is the error in the DNN error log. It fails when reading the de-de resx file. Maybe this has a knock on effect. I would try fixing that... or try to delete the de-de resx and see if it works on the default resx file.
