### ISSUE TITLE
v4.1.4: 3 Months at Pre-Release.

### ISSUE THREAD

**Issue by Suprawow** [openstore-ecommerce/OpenStore#110]
Could v4.1.4 be moved to "Latest Release" yet?
I'm unable to publish "Pre-Release" versions and it's been like this for about 3 months now.
Thank you.

**Comment by DNNMonster** [comment]
Dave should be able to make that happen for you.  Give him a moment or two.

**Comment by Suprawow** [comment]
That would be brilliant! Thank you. :-)

**Comment by leedavi** [comment]
OK,  I'll do it.  I usually wait until I have a site live with the version before I set it to the release.  I do have sites running on this, I must have forgot to change it.

Thx for the heads up.

**Comment by Suprawow** [comment]
Thanks for addressing it Dave. Very much appreciated.
