### ISSUE TITLE
ClientData duplicate

### ISSUE THREAD

**Issue by leedavi** [openstore-ecommerce/OpenStore#115]
If you create a record for client data like this...

                                    var clientData = new ClientData(PortalSettings.Current.PortalId, userid);

If you save...

                                    clientData.Save();

It will create a duplicate.

The workaround is to read the datarecord and then update(NBrightINfo)

                                    var objCtrl = new NBrightBuyController();
                                    var clientData = new ClientData(PortalSettings.Current.PortalId, userid);
                                    var dataRecord = objCtrl.GetByType(PortalSettings.Current.PortalId, -1, "CLIENT", userid.ToString(""));

                                    dataRecord.SetXmlProperty("genxml/checkbox/hasaccount", "True");
                                    dataRecord.SetXmlProperty("genxml/dropdownlist/depot", DepotRef);

                                    dataRecord.SetXmlProperty("genxml/import", ""); // create node
                                    dataRecord.SetXmlProperty("genxml/import/tircode", tircode);
    

                                    clientData.Update(dataRecord);

**Comment by DNNMonster** [comment]
The feature branch for client data caching may address this issue.  Ultimately there is a -1 getting to the NBrightBuy_Update sproc when it shouldn't.
