### ISSUE TITLE
Iframe youtube embed code not saving in Editor

### ISSUE THREAD

**Issue by fkw** [openstore-ecommerce/OpenStore#12]
Source is not saving even if you go back in normal mode before saving.

**Comment by leedavi** [comment]
No solution ATM.  The standard solution is to allow extendedcontect using:

	config.allowedContent = true;

or an iframe identifier.  We already use this and still iframers are stripped.

Tried reverting to v4.1.3, still  iframes are stripped.

tried other options as well, nothing seems to stop the iframe from being stripped by ckeditor.

**Comment by leedavi** [comment]
Update ln v4.0.4 it was a security addition ot the NbBright Template system to stop cross site scripting.  There is an option to ignore.  I've ignored for managers and administrators.
