### ISSUE TITLE
ProductOptionsAsRadioButtons bug with unique id's

### ISSUE THREAD

**Issue by trouble2** [openstore-ecommerce/OpenStore#143]
Please change to:

strOut += "<input type='checkbox' id='optionrb" + (index + 1) + cnt + "' name='optionrb" + (index + 1) + "' " + selected + " value='" + optval.GetXmlProperty("genxml/hidden/optionvalueid") + "'>";
                        strOut += "<label for='optionrb" + (index + 1) + cnt + "'>" + optval.GetXmlProperty("genxml/lang/genxml/textbox/txtoptionvaluedesc") + addedcostdisplay + "</label>";

In: render/NBrightBuyRazorTokens.cs line 479 and 480.
So add the '+ cnt +'  part to the id, and the for part, so the id's of the radiobuttons are unique.

**Comment by leedavi** [comment]
OK I added this..

                        strOut += "<input type='checkbox' id='optionrb" + (index + 1) + cnt + "' name='optionrb" + (index + 1) + "' " + selected + " value='" + optval.GetXmlProperty("genxml/hidden/optionvalueid") + "'>";
                        strOut += "<label for='optionrb" + (index + 1) + "'>" + optval.GetXmlProperty("genxml/lang/genxml/textbox/txtoptionvaluedesc") + addedcostdisplay + "</label>";


But , the label is not anything liek you posted?

**Comment by trouble2** [comment]
Ok, just reviewed the whole function:

        public IEncodedString ProductOptionAsRadiobuttons(ProductData productdata, int index, String attributes = "", Boolean required = false)
        {
            var strOut = "";

            var objL = productdata.Options;

            if (objL.Count > index)
            {
                var requiredattr = "";
                var obj = objL[index];
                var optid = obj.GetXmlProperty("genxml/hidden/optionid");
                var optvalList = productdata.GetOptionValuesById(optid);
                if (obj.GetXmlPropertyBool("genxml/checkbox/optrequired")) required = true;

                strOut += "<div  class='option option" + (index + 1) + "' " + attributes + ">";
                strOut += "<span class='optionname optionname" + (index + 1) + "'>" + obj.GetXmlProperty("genxml/lang/genxml/textbox/txtoptiondesc") + "</span>";
                strOut += "<span class='optionvalue optionvalue" + (index + 1) + "'>";

                if (optvalList.Count > 1)
                {
                    if (required) requiredattr = " required='' name='optionddl" + (index + 1) + "'"; // name also needs to be added for JQuery Validation to work correctly

                    var cnt = 0;

                    foreach (var optval in optvalList)
                    {
                        var addcost = optval.GetXmlPropertyDouble("genxml/textbox/txtaddedcost");
                        var addedcostdisplay = "";
                        //put a span around it, so at least we can hide with css...
                        if (addcost > 0)
                        {
                            addedcostdisplay = " <span class='addcst addcs" + (index + 1) + cnt + "'>(+" + NBrightBuyUtils.FormatToStoreCurrency(addcost) + ")</span>";
                        }

                        var selected = "";
                        if ((cnt == 0) && required)
                        {
                            selected = "checked='checked'";
                        }
                        cnt += 1;

                        strOut += "<input type='checkbox' id='optionrb" + (index + 1) + cnt + "' name='optionrb" + (index + 1) + "' " + selected + " value='" + optval.GetXmlProperty("genxml/hidden/optionvalueid") + "'>";
                        strOut += "<label for='optionrb" + (index + 1) + cnt + "'>" + optval.GetXmlProperty("genxml/lang/genxml/textbox/txtoptionvaluedesc") + addedcostdisplay + "</label>";
                    }

                }

                if (optvalList.Count == 1)
                {
                    //checkbox
                    foreach (var optval in optvalList)
                    {
                        var addcost = optval.GetXmlPropertyDouble("genxml/textbox/txtaddedcost");
                        var addedcostdisplay = "";
                        if (addcost > 0)
                        {
                            addedcostdisplay = " <span class='addcst addcs" + (index + 1) + "'>(+" + NBrightBuyUtils.FormatToStoreCurrency(addcost) + ")</span>";
                        }

                        strOut += "    <input id='optionchk" + (index + 1) + "' type='checkbox' " + attributes + " update='save' /><label>" + optval.GetXmlProperty("genxml/lang/genxml/textbox/txtoptionvaluedesc") + addedcostdisplay + "</label>";
                    }
                }

                if (optvalList.Count == 0)
                {
                    // textbox
                    if (required) requiredattr = " required='' name='optiontxt" + (index + 1) + "'"; // name also needs to be added for JQuery Validation to work correctly
                    strOut += "<input id='optiontxt" + (index + 1) + "' " + requiredattr + " update='save' type='text' />";
                }

                strOut += "<input id='optionid" + (index + 1) + "' update='save' type='hidden' value='" + optid + "' />";
                strOut += "</span>";
                strOut += "</div>";

            }


            return new RawString(strOut);
        }

**Comment by leedavi** [comment]
OK, I have blindly added it to the develop branch.  It can't break anything else, so I have no problem with adding it.  But, let me know if it's OK now.

**Comment by trouble2** [comment]
Thanks

**Comment by trouble2** [comment]
Hi Dave,

We tried to work with the developers version but could not build it.
So, any idea when it will be included in the beta version, so we can test it?


Van: David Lee ***@***.***>
Verzonden: maandag 3 mei 2021 09:22
Aan: openstore-ecommerce/OpenStore ***@***.***>
CC: Marnix Bouwman ***@***.***>; Author ***@***.***>
Onderwerp: Re: [openstore-ecommerce/OpenStore] ProductOptionsAsRadioButtons bug with unique id's (#143)


OK, I have blindly added it to the develop branch. It can't break anything else, so I have no problem with adding it. But, let me know if it's OK now.

**Comment by leedavi** [comment]
Yes, it will be the DNNpackager.  https://github.com/leedavi/DNNpackager

You can try and install that...  OR ...

remove the call to if after the build.  It will create the assembly, just copy it into the beta install zip and it should work.

![image](https://user-images.githubusercontent.com/5583141/117643510-c5f88800-b188-11eb-9d22-ab911287d03d.png)


.
