### ISSUE TITLE
OpenStoreDemo.template Missing

### ISSUE THREAD

**Issue by qualitymanager** [openstore-ecommerce/OpenStore#19]
The [documentation page](https://doc.openstore-ecommerce.com/#PM6kR1fXdf) in the installation section says...

> Optional : Once installed you can then apply the Open Store DNN site template.  This can be found in the default portal and is called "OpenStoreDemo.template", you can use the Site Wizard to apply the template.  This is an optional step to help speed up the setup of the website, but you can choose to apply the modules onto the page yourself..

But the file **OpenStoreDemo.template** is not included in OpenStore_4.0.4_Install.zip
Tried the 4.0.4 install in DNN7 Fresh Install and a DNN7 to 8 Upgrade (to keep Site Wizard Module)
Tried installing NBrightDNN_8.5.1_Install.zip in case it was in that.

Is this file removed from the 4.0.4.0 install zip now that fresh installs of dnn9 no longer include site wizard?

Any ideas?
I am trying to use the wizard to see examples of what the module settings should be as ive tried installing in a dnn9 site and manually setting the modules up but im struggling to get most modules to work and wanted to see a basic working setup to see what mistakes i was making.

**Comment by leedavi** [comment]
The template is on v4 release: 
https://github.com/openstore-ecommerce/OpenStore/releases/tag/v4.0.0.4

It has been created for DNN8, so I'm unsure if it'll work on DNN9. We stopped releasing it becuase it was confusing people. I think we need to rework the instruction.  But Have a read of these:

https://doc.openstore-ecommerce.com/#j8SfFNbvXH

It gives agood idea of how to setup.  We need to get sometime to make the installation as simple as possible, but it's not there yet.
