### ISSUE TITLE
PayPal ERROR: System.FormatException

### ISSUE THREAD

**Issue by inu-web** [openstore-ecommerce/OpenStore#190]
Hi
please can somebody give me a hint what the following error may be caused by?
I already posted this at https://github.com/openstore-ecommerce/OS_PayPal/issues/3 but I didnt receive any reply for over a week now - so I thought I try to find some help here ... 

I am using Openstore version 4.1.5 on DNN 9.3.2 and followed the instructions in the integrator manual and various hints I found via google-search.

I configured anything as I remembered how to do it but the "old" documentation from nb-Store seems no more available - The paypal integration was described in more detail there than in the current documentation - as far as I remember.

I am seeing this Error in the BackOffice/Admin/OS_Paypal Payment Plugin Settings on the very bottom of the page...
OS_PayPal ERROR: System.FormatException: Input string was not in a correct format. at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal) at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info) at System.Convert.ToInt32(String value) at OS_PayPal.PayPalIpnParameters..ctor(HttpRequest ipnRequest) at OS_PayPal.DNN.NBrightStore.OSPayPalNotify.ProcessRequest(HttpContext context)

The transactions payd with paypal work and I am returned to the payment_Ok template/page
But the Orders-Area in BackOffice always shows "Payment not verified" instead of "payment OK"
![130963961-9ae2b454-e6f8-4433-85b9-7a546294a55c](https://user-images.githubusercontent.com/7883518/131964045-2b7c31ef-66d8-4fc1-9414-835eed4afd85.png)

Thanks in advance and kind regards
Gerald

**Comment by DNNMonster** [comment]
See below

https://github.com/openstore-ecommerce/OS_PayPal/issues/3
