### ISSUE TITLE
Product Options As Radio Buttons does not save data

### ISSUE THREAD

**Issue by DNNMonster** [openstore-ecommerce/OpenStore#195]
The ProductOptionsAsRadiobuttons token renders but the selected options do not get saved when added to the cart.

**Comment by trouble2** [comment]
Great!, when will this be added, cause I tried the 4.1.7 release, but I don't think it is in there is it?

**Comment by DNNMonster** [comment]
You can check it out in the pre-release for 4.1.8 which I suspect will get officially released shortly.
