### ISSUE TITLE
New resources for es-ES language

### ISSUE THREAD

**Issue by ufoloko** [openstore-ecommerce/OpenStore#224]
I have translated all files for es-ES language, im attaching zip with all files here. Sorry for use this way but im not familiar with github yet

[es-ES.zip](https://github.com/openstore-ecommerce/OpenStore/files/7765364/es-ES.zip)
.

**Comment by DNNMonster** [comment]
There is feature branch that we'll merge after a few days so others can have a chance to review it.  Thanks!
