### ISSUE TITLE
Return button to products page

### ISSUE THREAD

**Issue by ufoloko** [openstore-ecommerce/OpenStore#229]
Actually module have razor function EditUrl() for templates, this function redirect edit page for a product in admin store. There you have the buttons save and exit, and return, but those buttons take the user back to the products list inside admin, not the original page where edit link was clicked.

Link generated have parameters &rtntab=XX&rtnmid=XX, so, the module should be able to take back to the original page using those parameters, just like in the older version NBStore 2.

This function allows to place a button or link for edit a product directly from website. without to go to the admin store and search the product, etc. It should be great to have that option again.

**Comment by DNNMonster** [comment]
Can the EditUrl token work for you?
`@if ((DotNetNuke.Security.PortalSecurity.IsInRole("Administrators") || (DotNetNuke.Security.PortalSecurity.IsInRole("ClientEditor"))
{
    <a href="@EditUrl(info, Model)"><i title="Edit" class="fa fa-edit fa-fw"></i></a>
}`

**Comment by ufoloko** [comment]
Yes I'm using right now EditUrl but the problem is that after edit the product or cancel the edition buttons return to product list not to page where made click for edit 

I was checking that in code and it appears is not implemented that option
