### ISSUE TITLE
Paging not working when category is selected

### ISSUE THREAD

**Issue by ufoloko** [openstore-ecommerce/OpenStore#233]
I have some products (more than 5000) in module, and if open products page, without any category(default category in settings) paging works without any problem. But if you select from menu any category, paging stops working, and everytime I click on a page, always is returning the first page of products

Anybody have an idea what can be the problem ?

**Comment by ufoloko** [comment]
Again, it was a settings thing, I had set lowecase transform for urls in DNN Admin, this rewrites page=X parameter and is not being recognized by the module for paging.

**Comment by DNNMonster** [comment]
Thanks for reporting that back in case someone else bumps into it.
