### ISSUE TITLE
Disable on promo code doesn't work : the amount is deducted in the basket even if disabled

### ISSUE THREAD

**Issue by CatsLEE** [openstore-ecommerce/OpenStore#257]
![image](https://user-images.githubusercontent.com/93389194/157825671-60c93919-0f11-4e78-b205-38462918cf43.png)

**Comment by DNNMonster** [comment]
There is a bugfix branch that should fix the disabled issue for Discount Codes.  Let's let eyes review it before it gets merged it into develop.  https://github.com/openstore-ecommerce/OpenStore/tree/bugfix/257-disabled-discounts
