### ISSUE TITLE
Add product throws an error

### ISSUE THREAD

**Issue by Rodien** [openstore-ecommerce/OpenStore#258]
This issue is related to version v4.1.10.

I think that this has something to do with the enhancement made for "Product copy". (Add Categories, Properties, clients and Related products to Product copy.)

Right now, if you try to add a new product an error gets thrown but if you go back to the list of products, you'll see an empty product.
With the name " - copy". 

**This is the error: **
System.NullReferenceException: Object reference not set to an instance of an object. at Nevoweb.DNN.NBrightBuy.Components.ProductData.GetRelatedProducts() at Nevoweb.DNN.NBrightBuy.Components.Products.ProductFunctions.ProductSave(HttpContext context, Boolean newrecord) at Nevoweb.DNN.NBrightBuy.Components.Products.ProductFunctions.ProductAdminAddNew(HttpContext context)

@leedavi

**Comment by Rodien** [comment]
I have installed open store on a clean DNN installation.

DNN: 9102, 9.8.2
Open store: v4.1.10
NBrightTemplateSys: 8.6.3, 8.7.0

When I click on "Add" it throws this error
NullReferenceException: Object reference not set to an instance of an object. at Nevoweb.DNN.NBrightBuy.Components.ProductData.GetRelatedProducts() in C:\inetpub\dnn9102dev\Website\DesktopModules\NBright\NBrightBuy\Components\Product\ProductData.cs:line 581 at Nevoweb.DNN.NBrightBuy.Components.Products.ProductFunctions.ProductSave(HttpContext context, Boolean newrecord) in C:\inetpub\dnn9102dev\Website\DesktopModules\NBright\NBrightBuy\Components\Product\ProductFunctions.cs:line 352 at Nevoweb.DNN.NBrightBuy.Components.Products.ProductFunctions.ProductAdminAddNew(HttpContext context) in C:\inetpub\dnn9102dev\Website\DesktopModules\NBright\NBrightBuy\Components\Product\ProductFunctions.cs:line 262

![image](https://user-images.githubusercontent.com/50739829/158672202-153ed80f-b095-4077-9bc6-278067fde374.png)




I am trying to add a new product, so I do not know why it's trying to get related products.

**Comment by leedavi** [comment]
OK I see.  Yes can recreate. My mistake on this,.  I'll fix ASAP.  (tomorrow or the weekend)

**Comment by leedavi** [comment]
@Rodien - The fix is here: https://github.com/openstore-ecommerce/OpenStore/releases/tag/v4.1.11

@DNNMonster - Thx for the help.  I've taken your fix, plus altered the logic to have less effect on the release.  Plus, removed some redundant code.

**Comment by Rodien** [comment]
Thanks guys. 

I tested it and everything seems to be working.

**Comment by leedavi** [comment]
OK great.  Thanks for getting back to us.
