### ISSUE TITLE
CartList.cshtml template allways loaded from desktopmodules default

### ISSUE THREAD

**Issue by sboshuis** [openstore-ecommerce/OpenStore#37]
CartList.cshtml template allways loaded from desktopmodules default folder. 

We load the fullcart.cshtml from the ClassicAjax folder (portals) and that works fine but that template should load the cartlist as well from that ClassicAjax folder but it allways takes that template from the
desktopmodules default folder (default/default).

Thanks

**Comment by leedavi** [comment]
Did you alter the FullCart.cshtml to change the caftlist path to the correct one?

    @RenderTemplate("\\DesktopModules\\NBright\\NBrightBuy\\Themes\\Default\\Default\\CartList.cshtml", Model)
