### ISSUE TITLE
Cant Upload images or documents 

### ISSUE THREAD

**Issue by xwareinnovations** [openstore-ecommerce/OpenStore#44]
Brand New install of OS v4.0.5

I have tried on multiple dnn installs  ( dnn version 9.1  and 9.2) and get the same problem

I even tried upgrading a nbs v3.6.5 that was working and got the same error after upgrade. 

I've tried v4.05 and v4.06 and both have the same issue 

and I cannot upload images.  or documents

System.NullReferenceException: Object reference not set to an instance of an object. at NBrightDNN.DnnUtils.Encrypt(String value, String passkey) at Nevoweb.DNN.NBrightBuy.Components.Products.ProductFunctions.UpdateProductImages(HttpContext context) at Nevoweb.DNN.NBrightBuy.Components.Products.ProductFunctions.ProcessCommand(String paramCmd, HttpContext context, String editlang, String uilang) at Nevoweb.DNN.NBrightBuy.XmlConnector.ProcessRequest(HttpContext context)

**Comment by leedavi** [comment]
OK, like I've said on the forum.  Can you check you app pool permissions and the OpenStore folders that are created at portal level.

**Comment by leedavi** [comment]
Just tested on OSv4 a new install on DNN9.3 and the image upload works.

**Comment by JoeAucoin** [comment]
From my experience this is a folder permissions issue easily fixed by resetting permissions using the Digital Asset Management module (AKA File Management, AKA Site Assets). I saw this happen in sites that were previously upgraded from earlier versions of DNN.

**Comment by xwareinnovations** [comment]
its doing it on 3 completley seperate servers and if it were a permission issue wouldn't it affect the server that was running NBS 3.6.5?

**Comment by leedavi** [comment]
Do the OpenStore folders exist?

Check the permissions of those folders and check the app pool identify can read and write to them.

This does sound like a permisisosn issue.  I don't think this is OpenStore, like I've said, I can upload images onto a new install that I did yesterday.   The fact docs and images don't work would also indicate a permisisons issue with the folders.

Do you have any JS errors on the page?

**Comment by xwareinnovations** [comment]
i have checked the permissions and the app pool identity has full control

all 5 folders exist
NBSTemp
NBStore\clientuploads
NBStore\docs
NBStore\images
NBStore\uploads

what i did notice tho is that NBSTemp folder is for the first time ever completley empty.  not sure if its related

**Comment by leedavi** [comment]
The NBSTemp is cleared down periodically by the scheduler, so that should not be the issue.

Can't think what else could be wrong.  I can have a quick look at the Setting in Admin is you can pass me a Private message, with login details, on the forum.

Have you tried it from different browser?  What about JS errors?  could be a old js file?  Edge is a pain with caching, I've moved to chrome for development.

**Comment by xwareinnovations** [comment]
im getting no browser errors in the console. and ive tried with both edge and chrome. 

I changed app pools.  ive completely uninstalled the OpenStore modules , then reinstalled 

im going to start uninstalling 3rd party modules one at a time and try to see if its one of them.  


if that doesn't work ill recreate the site from scratch and see if that works

**Comment by xwareinnovations** [comment]
here is a list of my settings

<genxml>
  <files>
    <ctrl>emaillogo</ctrl>
  </files>
  <hidden>
    <backofficetabid>174</backofficetabid>
    <imageresize>700</imageresize>
    <hidemaillogo />
    <hidinfoemaillogo>Img=True</hidinfoemaillogo>
    <countrysortorder />
    <rootmappath>C:\HostingSpaces\Fran@customfp.net\customfp.net\wwwroot\</rootmappath>
  </hidden>
  <textbox>
    <adminemail>Ryan@xwinn.com</adminemail>
    <manageremail>Ryan@xwinn.com</manageremail>
    <supportemail>Ryan@xwinn.com</supportemail>
    <salesemail>Ryan@xwinn.com</salesemail>
    <websiteurl>https://customfp.net</websiteurl>
    <storeattention />
    <storecompany />
    <storepostbox />
    <storeaddressline1 />
    <storeaddressline2 />
    <storecity />
    <storeregion />
    <storepostcode />
    <storephone />
    <storetaxnumber />
    <bankname />
    <bankaccountname />
    <bankaccountnumber />
    <storename>Custom Fireplaces and More</storename>
    <twitterpage />
    <facebookpage />
    <addthispubid />
    <sharingwidget />
    <folderimages>NBStore\images</folderimages>
    <folderdocs>NBStore\docs</folderdocs>
    <folderuploads>NBStore\uploads</folderuploads>
    <folderclientuploads>NBStore\clientuploads</folderclientuploads>
    <fileregexpr>^.*\.(txt|gif|jpe?g|jpg|png|pdf|doc|docx|xls|xlsx|zip|csv|xml)</fileregexpr>
    <pagesize>30</pagesize>
    <productsearchmod />
    <minimumstocklevel>0</minimumstocklevel>
    <themefolder>Default</themefolder>
    <emailthemefolder>Default</emailthemefolder>
    <ckeditorcdn>https://cdn.ckeditor.com/4.9.2/standard/ckeditor.js</ckeditorcdn>
    <adminpin>2667</adminpin>
    <dealerrole>Dealer</dealerrole>
    <orderprefix />
    <productimageresize>960</productimageresize>
    <bonoimageicon>&lt;i class="fa fa-picture-o fa-5x"&gt;&lt;/i&gt;</bonoimageicon>
    <boclass>nbstore</boclass>
    <currencysymbol>$</currencysymbol>
  </textbox>
  <checkbox>
    <allowupload>True</allowupload>
    <enablefavorites>False</enablefavorites>
    <enablemyorders>False</enablemyorders>
    <enablemyprofile>False</enablemyprofile>
    <enablemyaddress>False</enablemyaddress>
    <cataloguemode>False</cataloguemode>
    <pageactions>False</pageactions>
    <devoptions>False</devoptions>
    <debug.mode>False</debug.mode>
    <debugfileout>False</debugfileout>
    <enablefilelogging>False</enablefilelogging>
    <activate404>True</activate404>
    <singlepaymentoption>False</singlepaymentoption>
    <enabledealer>False</enabledealer>
    <copyorderto>True</copyorderto>
    <subscribenewsletter>True</subscribenewsletter>
    <checkoutpromocode>True</checkoutpromocode>
    <checkouttaxcode>True</checkouttaxcode>
    <gdpr>True</gdpr>
    <chkgroupresults>True</chkgroupresults>
    <shareproducts>False</shareproducts>
    <sharecategories>False</sharecategories>
    <shareorders>False</shareorders>
    <alloweditorder>False</alloweditorder>
    <sharedproductsflag />
  </checkbox>
  <dropdownlist>
    <storecountry selectedtext="United_x0020_States">US</storecountry>
    <productlisttab selectedtext="Activity_x0020_Feed">56</productlisttab>
    <ddldetailtabid selectedtext="Activity_x0020_Feed">56</ddldetailtabid>
    <productsearchtab selectedtext="Activity_x0020_Feed">56</productsearchtab>
    <carttab selectedtext="Activity_x0020_Feed">56</carttab>
    <checkouttab selectedtext="Activity_x0020_Feed">56</checkouttab>
    <paymenttab selectedtext="Activity_x0020_Feed">56</paymenttab>
    <exittab selectedtext="Activity_x0020_Feed">56</exittab>
    <favoritestab selectedtext="Activity_x0020_Feed">56</favoritestab>
    <ordermanagertab selectedtext="Activity_x0020_Feed">56</ordermanagertab>
    <profiletab selectedtext="Activity_x0020_Feed">56</profiletab>
    <addressestab selectedtext="Activity_x0020_Feed">56</addressestab>
    <logintab selectedtext="Activity_x0020_Feed">56</logintab>
    <merchantculturecode selectedtext="English_x0020__x0028_United_x0020_States_x0029__x0020_:_x0020_en-US">en-US</merchantculturecode>
    <currencyculturecode selectedtext="English_x0020__x0028_United_x0020_States_x0029__x0020_:_x0020_en-US">en-US</currencyculturecode>
  </dropdownlist>
  <checkboxlist>
    <countrycodelist>
      <chk value="False" data="Country:AF">Afghanistan</chk>
      <chk value="False" data="Country:AL">Albania</chk>
      <chk value="False" data="Country:DZ">Algeria</chk>
      <chk value="False" data="Country:AS">American Samoa</chk>
      <chk value="False" data="Country:AD">Andorra</chk>
      <chk value="False" data="Country:AO">Angola</chk>
      <chk value="False" data="Country:AI">Anguilla</chk>
      <chk value="False" data="Country:AQ">Antarctica</chk>
      <chk value="False" data="Country:AG">Antigua and Barbuda</chk>
      <chk value="False" data="Country:AR">Argentina</chk>
      <chk value="False" data="Country:AM">Armenia</chk>
      <chk value="False" data="Country:AW">Aruba</chk>
      <chk value="False" data="Country:AU">Australia</chk>
      <chk value="False" data="Country:AT">Austria</chk>
      <chk value="False" data="Country:AZ">Azerbaijan</chk>
      <chk value="False" data="Country:BS">Bahamas</chk>
      <chk value="False" data="Country:BH">Bahrain</chk>
      <chk value="False" data="Country:BD">Bangladesh</chk>
      <chk value="False" data="Country:BB">Barbados</chk>
      <chk value="False" data="Country:BY">Belarus</chk>
      <chk value="False" data="Country:BE">Belgium</chk>
      <chk value="False" data="Country:BZ">Belize</chk>
      <chk value="False" data="Country:BJ">Benin</chk>
      <chk value="False" data="Country:BM">Bermuda</chk>
      <chk value="False" data="Country:BT">Bhutan</chk>
      <chk value="False" data="Country:BO">Bolivia</chk>
      <chk value="False" data="Country:BA">Bosnia and Herzegovina</chk>
      <chk value="False" data="Country:BW">Botswana</chk>
      <chk value="False" data="Country:BV">Bouvet Island</chk>
      <chk value="False" data="Country:BR">Brazil</chk>
      <chk value="False" data="Country:IO">British Indian Ocean Territory</chk>
      <chk value="False" data="Country:VG">British Virgin Islands</chk>
      <chk value="False" data="Country:BN">Brunei Darussalam</chk>
      <chk value="False" data="Country:BG">Bulgaria</chk>
      <chk value="False" data="Country:BF">Burkina Faso</chk>
      <chk value="False" data="Country:BI">Burundi</chk>
      <chk value="False" data="Country:KH">Cambodia</chk>
      <chk value="False" data="Country:CM">Cameroon</chk>
      <chk value="False" data="Country:CA">Canada</chk>
      <chk value="False" data="Country:CV">Cape Verde</chk>
      <chk value="False" data="Country:KY">Cayman Islands</chk>
      <chk value="False" data="Country:CF">Central African Republic</chk>
      <chk value="False" data="Country:TD">Chad</chk>
      <chk value="False" data="Country:CL">Chile</chk>
      <chk value="False" data="Country:CN">China</chk>
      <chk value="False" data="Country:CX">Christmas Island</chk>
      <chk value="False" data="Country:CC">Cocos</chk>
      <chk value="False" data="Country:CO">Colombia</chk>
      <chk value="False" data="Country:KM">Comoros</chk>
      <chk value="False" data="Country:CG">Congo - Brazzaville</chk>
      <chk value="False" data="Country:CD">Congo-Kinshasa</chk>
      <chk value="False" data="Country:CK">Cook Islands</chk>
      <chk value="False" data="Country:CR">Costa Rica</chk>
      <chk value="False" data="Country:HR">Croatia</chk>
      <chk value="False" data="Country:CU">Cuba</chk>
      <chk value="False" data="Country:CY">Cyprus</chk>
      <chk value="False" data="Country:CZ">Czech Republic</chk>
      <chk value="False" data="Country:DK">Denmark</chk>
      <chk value="False" data="Country:DJ">Djibouti</chk>
      <chk value="False" data="Country:DM">Dominica</chk>
      <chk value="False" data="Country:DO">Dominican Republic</chk>
      <chk value="False" data="Country:TP">East Timor</chk>
      <chk value="False" data="Country:EC">Ecuador</chk>
      <chk value="False" data="Country:EG">Egypt</chk>
      <chk value="False" data="Country:SV">El Salvador</chk>
      <chk value="False" data="Country:GQ">Equatorial Guinea</chk>
      <chk value="False" data="Country:ER">Eritrea</chk>
      <chk value="False" data="Country:EE">Estonia</chk>
      <chk value="False" data="Country:ET">Ethiopia</chk>
      <chk value="False" data="Country:FK">Falkland Islands</chk>
      <chk value="False" data="Country:FO">Faroe Islands</chk>
      <chk value="False" data="Country:FJ">Fiji</chk>
      <chk value="False" data="Country:FI">Finland</chk>
      <chk value="False" data="Country:FR">France</chk>
      <chk value="False" data="Country:GF">French Guiana</chk>
      <chk value="False" data="Country:PF">French Polynesia</chk>
      <chk value="False" data="Country:TF">French Southern Territories</chk>
      <chk value="False" data="Country:GA">Gabon</chk>
      <chk value="False" data="Country:GM">Gambia</chk>
      <chk value="False" data="Country:GE">Georgia</chk>
      <chk value="False" data="Country:DE">Germany</chk>
      <chk value="False" data="Country:GH">Ghana</chk>
      <chk value="False" data="Country:GI">Gibraltar</chk>
      <chk value="False" data="Country:GR">Greece</chk>
      <chk value="False" data="Country:GL">Greenland</chk>
      <chk value="False" data="Country:GD">Grenada</chk>
      <chk value="False" data="Country:GP">Guadeloupe</chk>
      <chk value="False" data="Country:GU">Guam</chk>
      <chk value="False" data="Country:GT">Guatemala</chk>
      <chk value="False" data="Country:GN">Guinea</chk>
      <chk value="False" data="Country:GW">Guinea-Bissau</chk>
      <chk value="False" data="Country:GY">Guyana</chk>
      <chk value="False" data="Country:HT">Haiti</chk>
      <chk value="False" data="Country:HM">Heard and McDonald Islands</chk>
      <chk value="False" data="Country:HN">Honduras</chk>
      <chk value="False" data="Country:HK">Hong Kong</chk>
      <chk value="False" data="Country:HU">Hungary</chk>
      <chk value="False" data="Country:IS">Iceland</chk>
      <chk value="False" data="Country:IN">India</chk>
      <chk value="False" data="Country:ID">Indonesia</chk>
      <chk value="False" data="Country:IR">Iran</chk>
      <chk value="False" data="Country:IQ">Iraq</chk>
      <chk value="False" data="Country:IE">Ireland</chk>
      <chk value="False" data="Country:IL">Israel</chk>
      <chk value="False" data="Country:IT">Italy</chk>
      <chk value="False" data="Country:CI">Ivory Coast</chk>
      <chk value="False" data="Country:JM">Jamaica</chk>
      <chk value="False" data="Country:JP">Japan</chk>
      <chk value="False" data="Country:JO">Jordan</chk>
      <chk value="False" data="Country:KZ">Kazakhstan</chk>
      <chk value="False" data="Country:KE">Kenya</chk>
      <chk value="False" data="Country:KI">Kiribati</chk>
      <chk value="False" data="Country:KW">Kuwait</chk>
      <chk value="False" data="Country:KG">Kyrgyzstan</chk>
      <chk value="False" data="Country:LA">Laos</chk>
      <chk value="False" data="Country:LV">Latvia</chk>
      <chk value="False" data="Country:LB">Lebanon</chk>
      <chk value="False" data="Country:LS">Lesotho</chk>
      <chk value="False" data="Country:LR">Liberia</chk>
      <chk value="False" data="Country:LY">Libya</chk>
      <chk value="False" data="Country:LI">Liechtenstein</chk>
      <chk value="False" data="Country:LT">Lithuania</chk>
      <chk value="False" data="Country:LU">Luxembourg</chk>
      <chk value="False" data="Country:MO">Macau</chk>
      <chk value="False" data="Country:MK">Macedonia</chk>
      <chk value="False" data="Country:MG">Madagascar</chk>
      <chk value="False" data="Country:MW">Malawi</chk>
      <chk value="False" data="Country:MY">Malaysia</chk>
      <chk value="False" data="Country:MV">Maldives</chk>
      <chk value="False" data="Country:ML">Mali</chk>
      <chk value="False" data="Country:MT">Malta</chk>
      <chk value="False" data="Country:MH">Marshall Islands</chk>
      <chk value="False" data="Country:MQ">Martinique</chk>
      <chk value="False" data="Country:MR">Mauritania</chk>
      <chk value="False" data="Country:MU">Mauritius</chk>
      <chk value="False" data="Country:YT">Mayotte</chk>
      <chk value="False" data="Country:MX">Mexico</chk>
      <chk value="False" data="Country:FM">Micronesia</chk>
      <chk value="False" data="Country:MD">Moldova</chk>
      <chk value="False" data="Country:MC">Monaco</chk>
      <chk value="False" data="Country:MN">Mongolia</chk>
      <chk value="False" data="Country:ME">Montenegro</chk>
      <chk value="False" data="Country:MS">Montserrat</chk>
      <chk value="False" data="Country:MA">Morocco</chk>
      <chk value="False" data="Country:MZ">Mozambique</chk>
      <chk value="False" data="Country:MM">Myanmar</chk>
      <chk value="False" data="Country:NA">Namibia</chk>
      <chk value="False" data="Country:NR">Nauru</chk>
      <chk value="False" data="Country:NP">Nepal</chk>
      <chk value="False" data="Country:NL">Netherlands</chk>
      <chk value="False" data="Country:AN">Netherlands Antilles</chk>
      <chk value="False" data="Country:NC">New Caledonia</chk>
      <chk value="False" data="Country:NZ">New Zealand</chk>
      <chk value="False" data="Country:NI">Nicaragua</chk>
      <chk value="False" data="Country:NE">Niger</chk>
      <chk value="False" data="Country:NG">Nigeria</chk>
      <chk value="False" data="Country:NU">Niue</chk>
      <chk value="False" data="Country:NF">Norfolk Island</chk>
      <chk value="False" data="Country:KP">North Korea</chk>
      <chk value="False" data="Country:MP">Northern Mariana Islands</chk>
      <chk value="False" data="Country:NO">Norway</chk>
      <chk value="False" data="Country:OM">Oman</chk>
      <chk value="False" data="Country:PK">Pakistan</chk>
      <chk value="False" data="Country:PW">Palau</chk>
      <chk value="False" data="Country:PA">Panama</chk>
      <chk value="False" data="Country:PG">Papua New Guinea</chk>
      <chk value="False" data="Country:PY">Paraguay</chk>
      <chk value="False" data="Country:PE">Peru</chk>
      <chk value="False" data="Country:PH">Philippines</chk>
      <chk value="False" data="Country:PN">Pitcairn</chk>
      <chk value="False" data="Country:PL">Poland</chk>
      <chk value="False" data="Country:PT">Portugal</chk>
      <chk value="False" data="Country:PR">Puerto Rico</chk>
      <chk value="False" data="Country:QA">Qatar</chk>
      <chk value="False" data="Country:RE">Reunion</chk>
      <chk value="False" data="Country:RO">Romania</chk>
      <chk value="False" data="Country:RU">Russian Federation</chk>
      <chk value="False" data="Country:RW">Rwanda</chk>
      <chk value="False" data="Country:GS">S. Georgia and S. Sandwich Islands</chk>
      <chk value="False" data="Country:KN">Saint Kitts and Nevis</chk>
      <chk value="False" data="Country:LC">Saint Lucia</chk>
      <chk value="False" data="Country:VC">Saint Vincent and The Grenadines</chk>
      <chk value="False" data="Country:WS">Samoa</chk>
      <chk value="False" data="Country:SM">San Marino</chk>
      <chk value="False" data="Country:ST">Sao Tome and Principe</chk>
      <chk value="False" data="Country:SA">Saudi Arabia</chk>
      <chk value="False" data="Country:SN">Senegal</chk>
      <chk value="False" data="Country:RS">Serbia</chk>
      <chk value="False" data="Country:SC">Seychelles</chk>
      <chk value="False" data="Country:SL">Sierra Leone</chk>
      <chk value="False" data="Country:SG">Singapore</chk>
      <chk value="False" data="Country:SK">Slovakia</chk>
      <chk value="False" data="Country:SI">Slovenia</chk>
      <chk value="False" data="Country:SB">Solomon Islands</chk>
      <chk value="False" data="Country:SO">Somalia</chk>
      <chk value="False" data="Country:ZA">South Africa</chk>
      <chk value="False" data="Country:KR">South Korea</chk>
      <chk value="False" data="Country:SU">Soviet Union</chk>
      <chk value="False" data="Country:ES">Spain</chk>
      <chk value="False" data="Country:LK">Sri Lanka</chk>
      <chk value="False" data="Country:SH">St. Helena</chk>
      <chk value="False" data="Country:PM">St. Pierre and Miquelon</chk>
      <chk value="False" data="Country:SD">Sudan</chk>
      <chk value="False" data="Country:SR">Suriname</chk>
      <chk value="False" data="Country:SJ">Svalbard and Jan Mayen Islands</chk>
      <chk value="False" data="Country:SZ">Swaziland</chk>
      <chk value="False" data="Country:SE">Sweden</chk>
      <chk value="False" data="Country:CH">Switzerland</chk>
      <chk value="False" data="Country:SY">Syria</chk>
      <chk value="False" data="Country:TW">Taiwan</chk>
      <chk value="False" data="Country:TJ">Tajikistan</chk>
      <chk value="False" data="Country:TZ">Tanzania</chk>
      <chk value="False" data="Country:TH">Thailand</chk>
      <chk value="False" data="Country:TL">Timor-Leste</chk>
      <chk value="False" data="Country:TG">Togo</chk>
      <chk value="False" data="Country:TK">Tokelau</chk>
      <chk value="False" data="Country:TO">Tonga</chk>
      <chk value="False" data="Country:TT">Trinidad and Tobago</chk>
      <chk value="False" data="Country:TN">Tunisia</chk>
      <chk value="False" data="Country:TR">Turkey</chk>
      <chk value="False" data="Country:TM">Turkmenistan</chk>
      <chk value="False" data="Country:TC">Turks and Caicos Islands</chk>
      <chk value="False" data="Country:TV">Tuvalu</chk>
      <chk value="False" data="Country:UG">Uganda</chk>
      <chk value="False" data="Country:UA">Ukraine</chk>
      <chk value="False" data="Country:AE">United Arab Emirates</chk>
      <chk value="False" data="Country:GB">United Kingdom</chk>
      <chk value="True" data="Country:US">United States</chk>
      <chk value="False" data="Country:UY">Uruguay</chk>
      <chk value="False" data="Country:UM">US Minor Outlying Islands</chk>
      <chk value="False" data="Country:VI">US Virgin Islands</chk>
      <chk value="False" data="Country:UZ">Uzbekistan</chk>
      <chk value="False" data="Country:VU">Vanuatu</chk>
      <chk value="False" data="Country:VE">Venezuela</chk>
      <chk value="False" data="Country:VN">Viet Nam</chk>
      <chk value="False" data="Country:WF">Wallis and Futuna Islands</chk>
      <chk value="False" data="Country:EH">Western Sahara</chk>
      <chk value="False" data="Country:YE">Yemen</chk>
      <chk value="False" data="Country:YU">Yugoslavia</chk>
      <chk value="False" data="Country:ZR">Zaire</chk>
      <chk value="False" data="Country:ZM">Zambia</chk>
      <chk value="False" data="Country:ZW">Zimbabwe</chk>
    </countrycodelist>
  </checkboxlist>
  <radiobuttonlist />
  <edt />
</genxml>

**Comment by leedavi** [comment]
Try removing the "@" from the file path

C:\HostingSpaces\Fran@customfp.net\customfp.net\wwwroot\

It's an odd char to have in there, I wonder if that is causing an issue.

**Comment by xwareinnovations** [comment]
so ive tried everything with no luck. 

so I finally deleted all the files in the website directories,  and copied over a fresh DNN 9.2 install

Deleted the Database and created a blank one

reinstalled all plugins that I was using before 

imported a backup I had of Open Store 

and recreated each page on my entire website.  but the uploads are now working again. 

no clue what the actual problem that was causing the issue was.

**Comment by leedavi** [comment]
If it's any help, I've had a couple of DNN installations like this.  Sometimes it's just easier and quicker to rebuild.  Usually when this kind of thing happens people always assume it must be OpenStore the problem and not DNN.  One of the disadvantages of building a complex system on a CMS, because OpenStore has no or little control of the environment.

But I'm glad you got it fix. :-)
