### ISSUE TITLE
Browse Product view is very Slow

### ISSUE THREAD

**Issue by msnahm** [openstore-ecommerce/OpenStore#49]
I use DNN 9.2.2 and Open Store 4.0.7, Pages for Product View and Detail page are very slow.
My website configured for using GZIP, JS and CSS minimizing but It has not been effective to speed.
Other pages in site are normal but the pages for OS is very slow, especially for first time.
Adjusting cache for OS modules with ClassicAjax template has another issues!
Please help me to resolve these problems.

**Comment by leedavi** [comment]
Make sure you turn off the "Debug Mode" in the Admin Settings of the store.  With debug mode on, caching is turned off.

The store uses razor, so it compiles the template on first entry, but then should cache and it should be very quick.

I've not seen any sites where the OS pages are slower than other DNN pages, or at least not noticeable.  So it makes me think something else might be going on here.

I've tested with 200,000 records in the DB and the select times where OK.  How many products do you have and how maybe bespoke templates and fields.  Maybe you bespoke changes are slowing things down?

**Comment by msnahm** [comment]
Thank you for your reply, "Debug Mode" is Off. My store is in "Catalogue mode" and default ClassicAjax template.

My Product page contains a Product View Module and Category Module, when I active Memory Cache for the page (300 Seconds) by click to any node of Product Category, thr page was remaining to first product view. Also in detail page by click in return button, product view appear as list model!
The reason for this issue can be the AJAX reasons?
Can I consider another check list for this problem?

**Comment by leedavi** [comment]
It could be a missing end point for the Ajax API, either by iis security or badly installed.

Have a look to see what errors are in the browser console.  It might be incompatible JS on the site.

**Comment by msnahm** [comment]
Dear Leedavi,
Our web site hosts in sharing plan, so I ticket this problem with support. High CPU usage is main reason of this issue when the the "Product page & detail" was clicked. Other web site Pages does not have any abnormal CPU usage.
Is any recommendation for CPU usage?

**Comment by leedavi** [comment]
It depends on the store size, page size, template designer, client usage, etc.

But we always put our clients e-commerce onto their own VPS.  With a minimum spec of:

1 vCore(s)
À partir de 2 GHz
6 Go de RAM
25 Go

You can get away with less RAM, but higher CPU speed is preferable.

This is the Minimum we use.  Obviously if you have a busy e-commerce more is better.

**Comment by DNNMonster** [comment]
Try changing the temp directory attribute of the compilation element below your system.web element in your web.config.  This may lessen the impact of any virus software that a shared host has monitoring the default asp.net temp directory.

**Comment by msnahm** [comment]
WOW!!! That's amazing!!! Your solution is what exactly I was looking for. Thank you so much. I couldn't actually put into words!!!
I change the Temp Directory to a sub folder of my website root. Is a way to change Cache Duration time or another parameter to better results?

**Comment by DNNMonster** [comment]
Glad it helped.  Improvements from others config changes you'll have to experiment with but that particular issue is a nasty one on shared hosting.  Looks like your checking the right boxes.
