### ISSUE TITLE
resize image to other value than 960

### ISSUE THREAD

**Issue by sboshuis** [openstore-ecommerce/OpenStore#58]
Hi,

If you change the storesetting it is saved and you can find the new value in the sql db just fine.

If you upload an image the image in the root folder is indeed changed to the new value

however there is also an image variant of this saved to the folder that seems to belong to the product you uploaded the image to. And that is allways resized to 960 and not the storesetting size. 

Not sure if this is it or maybe I am seeing something wrong but I think this is it:

ProductUtils.cs					
					
var imgSize = 960;
if (extension != null && extension.ToLower() == ".png")
{
	newImageFileName = ImgUtils.ResizeImageToPng(fullName, newImageFileName, imgSize);
}
else
{
	newImageFileName = ImgUtils.ResizeImageToJpg(fullName, newImageFileName, imgSize);
}

ProductFunctions.cs

var imgResize = StoreSettings.Current.GetInt(StoreSettingKeys.productimageresize);
if (imgResize == 0) imgResize = 960;
var imagepath = ResizeImage(fullName, imgResize);

**Comment by leedavi** [comment]
OK, Thanks.
Looks like ProductUtils needs updating to match ProductFunctions.
Can you create a pull request?
If not, I'll try and remember to include it on the next build.
