### ISSUE TITLE
cannot set module Output Cache Provider to None

### ISSUE THREAD

**Issue by seekthelight** [openstore-ecommerce/OpenStore#79]
Each module states that the output cache is "inherited" and is set to "memory". The page setting is set to "none". Therefore:
1) Where is it inherited from?
2) Why cant the modules save a setting of "none"?

You can't save the module settings unless you change it to "none", then it reverts back to "memory."

**Comment by leedavi** [comment]
I've seen this before... it is an error in the page JS.

I'm unsure what was done to fix this.  But if you look at the browser  console when you save, I think you'll see a JS error.

I "think" we updated DNN and it fix the issue.

What version of DNN are you using?
What version of OpenStore are you using?

**Comment by seekthelight** [comment]
DNN 9.5.0
Store 4.1.2

**Comment by leedavi** [comment]
I've not tried v9.5 yet. and v4.1.2 is not doing the JS error.

Did you check the browser console for a JS error when saving the settings?

Other other "Non- OpenStore" modules save the settings on the same page?

**Comment by seekthelight** [comment]
The other "non-OpenStore" modules do not have the same save issue.
The browser console has the following message:
TypeError: access to strict mode caller function is censored ScriptResource.axd:5:13769
    _doPostBack http://mi1printing.com/ScriptResource.axd?d=dwY9oWetJoJAtkhMnrSk_9l841byK4XvLa1IG9pjMZuY2UiXMi-aWmG1Mm7KLTcfAKTh6pFVAgSS-5JqMu3vKgB4dUXiEZ75RPJwHlMOcOqv2nFqsDxxN5OjaMgrIVvnNLSgLWynRt2VpdrD0&t=ffffffffecf19baa:5
    _doPostBackWithOptions http://mi1printing.com/ScriptResource.axd?d=dwY9oWetJoJAtkhMnrSk_9l841byK4XvLa1IG9pjMZuY2UiXMi-aWmG1Mm7KLTcfAKTh6pFVAgSS-5JqMu3vKgB4dUXiEZ75RPJwHlMOcOqv2nFqsDxxN5OjaMgrIVvnNLSgLWynRt2VpdrD0&t=ffffffffecf19baa:5
    createDelegate http://mi1printing.com/ScriptResource.axd?d=NJmAwtEo3Irzi5Ld6qAYJ7lKPMCYQAZJMG6fp3jULgRSa8hv10DJp1YYpPDLjp4550gSpRgq2CNiFuBnHvpTBJlpEP5kWkiMxyP_idO2Ik9S1STrLHK48E-Mtmgx9ZSiiqLAzQ2&t=ffffffffecf19baa:5
    <anonymous> http://mi1printing.com/Welcome/ctl/Module/ModuleId/416?ReturnURL=/&popUp=true line 80 > eval:1
    <anonymous> http://mi1printing.com/Welcome/ctl/Module/ModuleId/416?ReturnURL=/&popUp=true:80
    jQuery 3
    nbxget http://mi1printing.com/DesktopModules/NBright/NBrightBuy/Themes/config/js/nbbajax.js:31
    jQuery 4


The OpenStore module reads, "Output Cache Provider Inherited Memory"
The non-OpenStore module reads, "Output Cache Provider Memory"

**Comment by leedavi** [comment]
The "ScriptResource.axd?" is not OpenStore, and it appears your browser wants strict mode.  Are you using FireFox?

It looks like you have popups?  Try turning them off.

OpenStore uses a call in JS to get settings for the modules.  It could be there is a clash somewhere with DNN9.,5.

I've not tested against DNN9.5 yet, it was still in RC last time I looked, is it released now or have you got a RC?

1 - turn popups off.
2 - Try a different browser.
3 - Use the default skin.

**Comment by seekthelight** [comment]
I haven't completed the tests in Firefox, however, the issue does NOT persist in Edge. I have not checked chrome yet.

**Comment by seekthelight** [comment]
![image](https://user-images.githubusercontent.com/15399177/75278624-da44a500-57cf-11ea-848f-3c6d2f3771fd.png)

**Comment by seekthelight** [comment]
Popups are turned off in Firefox and the issue persists...

**Comment by leedavi** [comment]
OK, this might be some legacy JS in OpenStore, which is shown up by FF forcing strict mode.

I'll try and find the time to fix it in v4.1.3.

**Comment by leedavi** [comment]
This is of something in DNN using strict mode and a lot correctly does.  This cannot be fixed unless we alter the settings interface of all modules in OpenStore.

The workaround is simply to not use FireFox.
