### ISSUE TITLE
Unknown Issue Causes Back Office to Hang

### ISSUE THREAD

**Issue by seekthelight** [openstore-ecommerce/OpenStore#80]
Somehow, one of my images didn't upload correctly causing the back office to hang. I've tried validation; exporting, deleting, importing; changing browsers; clearing the cache and restarting the application; stopping the website and restarting the app pool; none of these potential solutions worked. 
If I delete the articles, everything goes back to normal. If I re-import the articles then it hangs. 
![image](https://user-images.githubusercontent.com/15399177/75307533-8eb2eb00-5811-11ea-9a1a-b5a1980fdced.png)

**Comment by seekthelight** [comment]
Okay, after some trial and error, I deleted the articles and reloaded just them without the properties and the categories. The hanging stopped. I retyped the categories because there aren't that many of them still no hang. I have deleted the broken images, still no hang. I haven't retyped the properties, but the original categories contained a dash and an ampersand sign which I have eliminated.

**Comment by seekthelight** [comment]
I think it may be the use of quotes in properties. When I try to save a properties that reads, 3.5" X 2" Size, it hangs. When I deleted that and changed it to 3.5 X 2 Size, it did not hang.

**Comment by leedavi** [comment]
OK, I'll check this.  There should be a filter in place to stop invalid chars, maybe it';s been removed for some reason.

When things go wring you can also try "Admin>Tools>Validate", it may take a long time with a large amount of products,

**Comment by seekthelight** [comment]
I did try "Admin>Tools>Validate" many times. It did not work also.

**Comment by leedavi** [comment]
OK, the validate might not be setup to deal with this kind of error.

**Comment by leedavi** [comment]
Is it possible to get a copy of this website, so I can have an example of it not working.  I've tried to find the issue, but I can not make it fail.
